version: '3.1'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: jlwalkerlg/bookable:prod
    ports:
      - 80:80
    working_dir: /var/www/bookable
    depends_on:
      - db
    restart: always

  queue:
    image: jlwalkerlg/bookable:prod
    working_dir: /var/www/bookable
    command: php /var/www/bookable/artisan queue:work --verbose --tries=3 --timeout=90
    depends_on:
      - web
    restart: always

  db:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    restart: always

volumes:
  dbdata:
