export const USER_ADD = 'USER_ADD';
export const USER_REMOVE = 'USER_REMOVE';

export const LOADING_FINISH = 'LOADING_FINISH';

export const BOOKS_FETCH = 'BOOKS_FETCH';

export const WISHLIST_ADD = 'WISHLIST_ADD';
export const WISHLIST_REMOVE = 'WISHLIST_REMOVE';
export const WISHLIST_HYDRATE = 'WISHLIST_HYDRATE';

export const CART_ADD = 'CART_ADD';
export const CART_REMOVE = 'CART_REMOVE';
export const CART_HYDRATE = 'CART_HYDRATE';

export const CATEGORIES_HYDRATE = 'CATEGORIES_HYDRATE';

export const HOME_BEST_SELLER_ADD = 'HOME_BEST_SELLER_ADD';
export const HOME_NEW_BOOKS_ADD = 'HOME_NEW_BOOKS_ADD';
export const HOME_FEATURED_BOOKS_ADD = 'HOME_FEATURED_BOOKS_ADD';
export const HOME_PENGUIN_BOOKS_ADD = 'HOME_PENGUIN_BOOKS_ADD';
export const HOME_TRENDING_BOOK_ADD = 'HOME_TRENDING_BOOK_ADD';

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
