export const USER_ADD = 'USER_ADD';
export const USER_REMOVE = 'USER_REMOVE';

export const LOADING_FINISH = 'LOADING_FINISH';

export const BOOKS_FETCH = 'BOOKS_FETCH';

export const WISHLIST_ADD = 'WISHLIST_ADD';
export const WISHLIST_REMOVE = 'WISHLIST_REMOVE';
export const WISHLIST_HYDRATE = 'WISHLIST_HYDRATE';

export const CART_ADD = 'CART_ADD';
export const CART_REMOVE = 'CART_REMOVE';
export const CART_HYDRATE = 'CART_HYDRATE';

export const CATEGORIES_HYDRATE = 'CATEGORIES_HYDRATE';
