export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

export const LOADING_FINISH = 'LOADING_FINISH';

export const BOOKS_FETCH = 'BOOKS_FETCH';

export const WISHLIST_ADD = 'WISHLIST_ADD';
export const WISHLIST_REMOVE = 'WISHLIST_REMOVE';
export const WISHLIST_HYDRATE = 'WISHLIST_HYDRATE';

export const CART_ADD = 'CART_ADD';
export const CART_REMOVE = 'CART_REMOVE';
export const CART_HYDRATE = 'CART_HYDRATE';

export const SHELVES_ADD = 'SHELVES_ADD';
export const SHELVES_REMOVE = 'SHELVES_REMOVE';
export const SHELVES_HYDRATE = 'SHELVES_HYDRATE';
